In [34]:
import numpy as np
import pandas as pd

In [35]:
pd.set_option('display.max_columns', None)

In [36]:
df = pd.read_csv("data/house-prices-advanced-regression-techniques/train.csv")

In [37]:
df.shape

(1460, 81)

In [38]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [39]:
keep_cols = ["MSSubClass"
             ,"MSZoning"
             ,"LotArea"
             ,"OverallQual"
             ,"OverallCond"
             ,"YearBuilt"
             ,"CentralAir"
             ,"FullBath"
             ,"HalfBath"
             ,"BedroomAbvGr"
             ,"GarageCars"
             ,"YrSold"
             ,"MoSold"
             ,"SalePrice"
             ]

categorical_vars = ["MSSubClass"
             ,"MSZoning"
             ,"CentralAir"
             ]

target = ["SalePrice"]

In [40]:
work_df = df[keep_cols]

In [41]:
work_df.head()

,MSSubClass,MSZoning,LotArea,OverallQual,OverallCond,YearBuilt,CentralAir,FullBath,HalfBath,BedroomAbvGr,GarageCars,YrSold,MoSold,SalePrice
0,60,RL,8450,7,5,2003,Y,2,1,3,2,2008,2,208500
1,20,RL,9600,6,8,1976,Y,2,0,3,2,2007,5,181500
2,60,RL,11250,7,5,2001,Y,2,1,3,2,2008,9,223500
3,70,RL,9550,7,5,1915,Y,1,0,3,3,2006,2,140000
4,60,RL,14260,8,5,2000,Y,2,1,4,3,2008,12,250000

In [42]:
work_df["YearsSinceBuild"] = work_df["YrSold"] - work_df["YearBuilt"]

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [43]:
work_df.drop(["YearBuilt", "YrSold"], axis=1, inplace=True)

In [44]:
work_df.isna().any()

MSSubClass         False
MSZoning           False
LotArea            False
OverallQual        False
OverallCond        False
CentralAir         False
FullBath           False
HalfBath           False
BedroomAbvGr       False
GarageCars         False
MoSold             False
SalePrice          False
YearsSinceBuild    False
dtype: bool

In [45]:
from sklearn import preprocessing

for var in categorical_vars:
    label_encoder = preprocessing.LabelEncoder()
    label_encoder.fit(work_df[var])
    work_df[var] = label_encoder.transform(work_df[var])

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [46]:
work_df.head()

,MSSubClass,MSZoning,LotArea,OverallQual,OverallCond,CentralAir,FullBath,HalfBath,BedroomAbvGr,GarageCars,MoSold,SalePrice,YearsSinceBuild
0,5,3,8450,7,5,1,2,1,3,2,2,208500,5
1,0,3,9600,6,8,1,2,0,3,2,5,181500,31
2,5,3,11250,7,5,1,2,1,3,2,9,223500,7
3,6,3,9550,7,5,1,1,0,3,3,2,140000,91
4,5,3,14260,8,5,1,2,1,4,3,12,250000,8

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(work_df.drop(target, axis=1), work_df[target], test_size=0.33, random_state=17)

In [50]:
from sklearn.ensemble import GradientBoostingRegressor

GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =17)
GBoost.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.05, loss='huber',
                          max_depth=4, max_features='sqrt', max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=15, min_samples_split=10,
                          min_weight_fraction_leaf=0.0, n_estimators=3000,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=17, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [59]:
preds = GBoost.predict(X_test)

diff = preds.reshape(482,1) - y_test

In [60]:
diff.mean()

SalePrice   -3037.844046
dtype: float64

In [61]:
diff

          SalePrice
703     4446.631245
1361  -73965.650556
937   -56136.650254
1330   22578.282608
113   -29825.225503
1428  -10476.826790
310    15809.924663
1142 -107412.378077
766   -18940.401180
836   -33921.517896
1099   26124.823408
449    -7523.188725
1342   19788.987507
648     4505.364935
104      869.051452
1185   28303.691207
1207   -1787.511990
799   -24450.982781
1136   11826.289210
408   -13132.020211
728    43825.943039
1166   26069.278472
136     2951.724300
1172  -10290.615569
891     3607.306517
1272  -10836.372185
692   -88563.710380
1395   38432.268005
167   -58070.312546
1021    3469.038979
...             ...
1183   17897.658136
142   -32565.344681
863   -15147.015194
715    13092.007358
1077  -22057.795021
755    -1380.888489
1258   24908.662358
919   -15162.613967
1007   -4129.441693
1457  -84527.621793
470    -3158.986590
929    -5769.275558
409   -64152.685684
399   -39004.699283
1455    9760.376625
362    36069.142416
545    40443.417642
1360   28320.666711
1195    9970.660133
564   -27269.847956
721     -586.019174
779     3108.336445
767    19925.459279
179    28044.285859
1000  -16726.631292
364    27934.182010
954     8690.415883
666    75637.533247
37    -15136.735710
197    -1712.488900

[482 rows x 1 columns]

In [62]:
import pickle

with open('house_prices_trained_model.pkl', 'wb') as f:
    pickle.dump(GBoost, f)